### ISSUE TITLE
Consider adding AbuseIO

### ISSUE THREAD

**Issue by kruisdraad** [hslatman/awesome-threat-intelligence#100]
Hi there,

nice list, would you consider adding AbuseIO (listed on GIT, details on https://abuse.io).

**Comment by hslatman** [comment]
Added in https://github.com/hslatman/awesome-threat-intelligence/commit/25d3ad4b64f62de97a97c1daf73cc663c9c50e84.

I think this is the proper category to put it in, as it (imo) only/mostly touches on the consumer side of threat intelligence feeds, correct?

**Comment by kruisdraad** [comment]
i can do a full spectrum by enabling parsers. The consumer side is just another addon to simpilify enduser reporting, but it could as easily be TI being downstreamed.
