### ISSUE TITLE
Repo Cleanup

### ISSUE THREAD

**Issue by iDuronto** [hslatman/awesome-threat-intelligence#148]
Hi there, thanks for the awesome list. However for someone who is cloning this repo, the repo size is huge, considering the number of branches (mostly stale and outdated) presently and their associated git history. Could this be a nicer cleaned up repo?

Regards.

**Comment by hslatman** [comment]
Hi @iDuronto,

Valid point. I've deleted the branches on GitHub.

 Closing this one.
