### ISSUE TITLE
Cymon to be discontinued April 30, 2019

### ISSUE THREAD

**Issue by strikaco** [hslatman/awesome-threat-intelligence#159]
FYI: Cymon.io currently has a banner on the homepage indicating it will be discontinued on April 30.

**Comment by hslatman** [comment]
Thanks you for the notice, @strikaco 

I will keep this issue open for the time being to keep track of it.

**Comment by hslatman** [comment]
The URL is now fully defunct. I've removed the entry. Thank you 😄
