### ISSUE TITLE
Dead link for Threat Intelligence: Collecting, Analysing, Evaluating 

### ISSUE THREAD

**Issue by crattis** [hslatman/awesome-threat-intelligence#170]
The link currently attached to Threat Intelligence: Collecting, Analysing, Evaluating under Research, Standards & Books is dead. It redirects to a 404 error.

This link appears to lead to the same white paper:
hXXps://www.mwrinfosecurity[.]com/our-thinking/intelligent-threat-intelligence/

White paper link from above page:
hXXps://www.mwrinfosecurity[.]com/assets/Whitepapers/Threat-Intelligence-Whitepaper.pdf

**Comment by hslatman** [comment]
I have updated the link. Thank you for the heads-up 😄
