### ISSUE TITLE
Talos Aspis link is dead

### ISSUE THREAD

**Issue by graememeyer** [hslatman/awesome-threat-intelligence#181]
The Talos Aspis link 404s, not sure if this threat feed has moved or is no longer available.

Update: 

The nothink.org link blank screens - looks like the feeds have been split out and are enumerated on the homepage. 

I've changed the title of this issue and will list any other dead/problematic links I notice here.

**Comment by hslatman** [comment]
I've removed the first and updated the second link in https://github.com/hslatman/awesome-threat-intelligence/pull/185.
