### ISSUE TITLE
Ransomware Tracker has been discontinued

### ISSUE THREAD

**Issue by FabioPedretti** [hslatman/awesome-threat-intelligence#187]
The Ransomware Tracker link https://ransomwaretracker.abuse.ch/ report this:
`# Ransomware Tracker has been discontinued on Dec 8th, 2019`
Maybe it should be removed from the list?

**Comment by hslatman** [comment]
I must've missed this issue, but I've cleaned this link out a while ago.

Thank you for the catch! 😄
