### ISSUE TITLE
https://intelstack.com link does not work

### ISSUE THREAD

**Issue by debarshri** [hslatman/awesome-threat-intelligence#207]
https://intelstack.com has become unavailable. Also the link from capitalone does not work.

**Comment by hslatman** [comment]
Thank you the heads up. I'm not sure if Critical Stack Intel is/will be open sourced by Capital One, but https://github.com/criticalstack seems to be somewhat alive, so I'll keep this issue open for now, so that I can check this in the (near) future.

**Comment by hslatman** [comment]
The link was removed in #271. I think it has been long enough, so I'll close this issue too. Thanks 🙂
