### ISSUE TITLE
Apility.io deprecated

### ISSUE THREAD

**Issue by tykkz** [hslatman/awesome-threat-intelligence#242]
Hello 👋

I found out that Apility.io is deprecated as per the following blog post and wanted to open this ticket.

https://auth0.com/blog/auth0-sunsets-signals/

Great project btw, thank you for putting together all this information.

**Comment by hslatman** [comment]
Hey @tykkz, coincidentally I've just merged this community contribution that removed it: https://github.com/hslatman/awesome-threat-intelligence/pull/238 😄 

Thanks for the heads up!
