### ISSUE TITLE
Add ThreatPinch Lookup

### ISSUE THREAD

**Issue by cloudtracer** [hslatman/awesome-threat-intelligence#59]
Free Chrome extension to add IOC reference tooltips to any webpage, can be used with any threat intelligence source that has an API.

https://chrome.google.com/webstore/detail/threatpinch-lookup/ljdgplocfnmnofbhpkjclbefmjoikgke

Disclaimer: I am the author of this tool.

**Comment by hslatman** [comment]
Thanks for your addition! Closing this as I added it in #61.
