### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by rpgoldman** [hslatman/awesome-threat-intelligence#85]
This link: "APT & Cyber Criminal Campaign Collection" to `https://github.com/gasgas4/APT_CyberCriminal_Campaign` is broken.

I can't get this resource through github search, either.  Looks like user "gasgas4" has pulled all their material off github.

**Comment by MauroEldritch** [comment]
https://web.archive.org/web/20170127083034/github.com/gasgas4/APT_CyberCriminal_Campaign

_Archived from Wayback Machine_

Not a solution by itself, but it seems like the author points its repo to another one in the Readme.md file. 
Let's give this a look and let me know if I can help you in some other way.
